// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    return $('img').attr('data-1x', function() {
      return $(this).attr('src');
    }).attr('data-2x', function() {
      return $(this).attr('src').replace('.', '@2x.');
    });
  });

}).call(this);
